column_translations = {
    "id": "报告ID",
    "create_by": "创建人",
    "create_time": "创建日期",
    "update_by": "更新人",
    "update_time": "更新日期",
    "sys_org_code": "所属部门",
    "equipment_id": "设备ID",
    "user_id": "用户ID",
    "name": "问卷调查名称",
    "result": "问诊结果",
    "ss_img": "舌面图像",
    "sx_img": "舌下图像",
    "img": "其他照片",
    "is_active": "是否生效",
    "is_report": "是否已出报告",
    "report_date": "报告日期",
    "is_push": "是否已推送",
    "healthy_status": "健康状态",
    "tongue_shape": "舌形",
    "tongue_color": "舌色",
    "tongue_bot": "舌底",
    "body_fluid": "津液",
    "liverwort": "苔质",
    "moss_color": "苔色",
    "sign": "舌诊标记",
    "pdf": "报告",
    "status": "是否已读",
    "choroid": "络脉",
    "syndrome": "证候",
    "remarks": "生成结果备注",
    "push_date": "推送时间",
    "receive_date": "接收结果时间",
    "check_status_code": "检查状态码",
    "qy_id": "企业ID",
    "frequency": "频率",
    "Total Records": "总记录",
    "Successful Reports": "成功报告"
}
